In [1]:
#!pip install tensorflow

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense     #Dense helps to adding layer
from tensorflow.keras import Sequential       #Initialized Data,Allowed layer in sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Load the Data

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/snehuuu28/Deep_Learning/main/ANN/Churn_Modelling.csv")

In [5]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [7]:
#Data Transformation

In [8]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [9]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.drop(columns=['Exited'])

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [12]:
df = pd.get_dummies(data=df, columns=['Geography', 'Gender'])
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1              True   
1                  1        112542.58       0             False   
2                  0        113931.57       1              True   
3                  0         93826.63       0              True   
4                  1         79084.10       0             False   
...              ...              ...     ...               ...   
9995               0         96270.64       0              True   
9996               1        101699.77       0              True   
9997               1         42085.58       1              True   
9998               0         92888.52       1             False   
9999               0         38190.78       0              True   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                 False            False           True        False  
1                 False             True           True        False  
2                 False            False           True        False  
3                 False            False           True        False  
4                 False             True           True        False  
...                 ...              ...            ...          ...  
9995              False            False          False         True  
9996              False            False          False         True  
9997              False            False           True        False  
9998               True            False          False         True  
9999              False            False           True        False  

[10000 rows x 14 columns]

In [13]:
df = df.astype(int)

In [14]:
df

CreditScore  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0             619   42       2        0              1          1   
1             608   41       1    83807              1          0   
2             502   42       8   159660              3          1   
3             699   39       1        0              2          0   
4             850   43       2   125510              1          1   
...           ...  ...     ...      ...            ...        ...   
9995          771   39       5        0              2          1   
9996          516   35      10    57369              1          1   
9997          709   36       7        0              1          0   
9998          772   42       3    75075              2          1   
9999          792   28       4   130142              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1           101348       1                 1   
1                  1           112542       0                 0   
2                  0           113931       1                 1   
3                  0            93826       0                 1   
4                  1            79084       0                 0   
...              ...              ...     ...               ...   
9995               0            96270       0                 1   
9996               1           101699       0                 1   
9997               1            42085       1                 1   
9998               0            92888       1                 0   
9999               0            38190       0                 1   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                     0                0              1            0  
1                     0                1              1            0  
2                     0                0              1            0  
3                     0                0              1            0  
4                     0                1              1            0  
...                 ...              ...            ...          ...  
9995                  0                0              0            1  
9996                  0                0              0            1  
9997                  0                0              1            0  
9998                  1                0              0            1  
9999                  0                0              1            0  

[10000 rows x 14 columns]

In [15]:
# Model Building

In [16]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [17]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2, random_state=1)

In [19]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [20]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics=['accuracy'])

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.5907 - loss: 0.6861
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5772 - loss: 0.6950
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5722 - loss: 0.6984
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5840 - loss: 0.6834
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5856 - loss: 0.6839
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5733 - loss: 0.6983
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5797 - loss: 0.6917
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5794 - loss: 0.6903
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5936 - loss: 0.6769
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5802 - loss: 0.6929
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5826 - loss: 0.6918
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [21]:
ypred = ann.predict(xtest)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [22]:
ypred

array([[0.64761174],
       [0.23670916],
       [0.40226975],
       ...,
       [0.19544582],
       [0.6314939 ],
       [0.5420156 ]], dtype=float32)

In [23]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [24]:
#print(classification_report(ytest,ypred))

In [25]:
a = 5
b = 10

In [26]:
a < b

True

In [27]:
a == b

False

In [28]:
False == 0
True == 1

True

In [29]:
ypred > 0.5

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [ True]])

In [30]:
ypred = ypred > 0.5
ypred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [ True]])

In [31]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [32]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.78      0.74      0.76      1585
           1       0.17      0.20      0.18       415

    accuracy                           0.63      2000
   macro avg       0.47      0.47      0.47      2000
weighted avg       0.65      0.63      0.64      2000



In [33]:
# Hyperparameter Tuning

In [34]:
!pip install -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 8.9 MB/s eta 0:00:00


In [35]:
# Tuning the ANN Model

In [36]:
import keras_tuner as kt

In [37]:
def optimizer_selection(hp):
  #Initialize model
  model = Sequential()
  #Add hidden layer
  model.add(Dense(units=10,activation='relu'))
  #Add output layer
  model.add(Dense(units=1, activation='sigmoid'))
  #Optimizer Selection
  optim = hp.Choice('optimizer', values=['sgd','adam','rmsprop'])
  model.compile(optimizer =optim,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [38]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [39]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 10s]
val_accuracy: 0.8105000257492065

Best val_accuracy So Far: 0.8105000257492065
Total elapsed time: 00h 00m 26s


In [40]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [41]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs=100,validation_data=(xtest,ytest))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.8135 - loss: 0.4323 - val_accuracy: 0.8120 - val_loss: 0.4293
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8122 - loss: 0.4379 - val_accuracy: 0.8145 - val_loss: 0.4201
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8193 - loss: 0.4175 - val_accuracy: 0.8210 - val_loss: 0.4103
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8264 - loss: 0.4067 - val_accuracy: 0.8285 - val_loss: 0.4013
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8276 - loss: 0.4025 - val_accuracy: 0.8385 - val_loss: 0.3917
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8389 - loss: 0.3845 - val_accuracy: 0.8425 - val_loss: 0.3831
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8442 - loss: 0.3750 - val_accuracy: 0.8455 - val_loss: 0.3752
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8426 - loss: 0.3734 - val_ac

In [42]:
model.evaluate(xtrain,ytrain)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8634 - loss: 0.3319


[0.33133256435394287, 0.8606250286102295]

In [43]:
# Regression

In [44]:
df = pd.read_csv("https://raw.githubusercontent.com/snehuuu28/Deep_Learning/main/ANN/Regression.csv")

In [45]:
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [46]:
x = df.iloc[:,1:]
y = df['price']

In [47]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [48]:
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.2, random_state=1)

In [49]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))
ann.add(Dense(units=20, activation='relu'))
ann.add(Dense(units=1))
ann.compile(optimizer='adam', loss='mse')
ann.fit(xtrain,ytrain, epochs=100, validation_data=(xtest,ytest))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 256623.0625 - val_loss: 262906.3125
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 251614.9844 - val_loss: 262640.0312
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 258168.0938 - val_loss: 262277.1250
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 254400.1562 - val_loss: 261632.9062
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 251551.6406 - val_loss: 260526.4375
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 253262.7969 - val_loss: 258725.3125
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 254457.4531 - val_loss: 255896.4531
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 252033.2812 - val_loss: 251743.5781
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 247924.8125 - val_loss: 245992.8438
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 238864.5469 - val_loss: 238476.6562
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/st

In [50]:
yp = ann.predict(xtest)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


array([[477.86353],
       [528.3991 ],
       [494.4102 ],
       [532.2218 ],
       [658.2664 ],
       [339.3361 ],
       [356.78897],
       [374.16635],
       [720.28784],
       [488.5646 ],
       [472.30206],
       [511.22836],
       [497.3847 ],
       [362.20053],
       [551.7341 ],
       [487.45596],
       [583.974  ],
       [553.9197 ],
       [485.6652 ],
       [500.55374],
       [457.4051 ],
       [593.43164],
       [443.94028],
       [581.4547 ],
       [425.8533 ],
       [526.6653 ],
       [377.7223 ],
       [493.96497],
       [545.147  ],
       [355.46582],
       [430.47824],
       [638.4934 ],
       [567.3123 ],
       [540.52673],
       [612.7044 ],
       [536.6084 ],
       [399.82507],
       [577.3818 ],
       [560.623  ],
       [509.21545],
       [423.2495 ],
       [731.3247 ],
       [528.95917],
       [533.639  ],
       [501.73117],
       [453.787  ],
       [515.4165 ],
       [525.714  ],
       [590.8106 ],
       [469.93137],


In [51]:
from sklearn.metrics import r2_score

In [52]:
r2_score(ytest,yp)

0.9613715966229606